# Access Credentials
client_id: <client_id>
secret: <client_secret>

# Whole city of San Diego, about 26K assets
# bbox: 32.97921188:-117.2786615,32.5796274808836:-117.000454314392

# Downtown San Diego
#bbox: 32.718987:-117.174244,32.707356:-117.154850

# Test value
bbox: 33.077762:-117.663817,32.559574:-116.584410

# San Diego Zones
default_zone: SD-IE-TRAFFIC
traffic_zone: SD-IE-TRAFFIC
parking_zone: SD-IE-PARKING
pedestrian_zone: SD-IE-PEDESTRIAN
environmental_zone: SD-IE-ENVIRONMENTAL
video_zone: SD-IE-VIDEO
image_zone: SD-IE-IMAGE

# Urls
uaa_url: https://auth.aa.cityiq.io
metadata_url: https://sandiego.cityiq.io
#media_url: https://sandiego.cityiq.io/api/v2/media/ondemand/assets
#event_url: https://sandiego.cityiq.io/api/v2/event/assets
event_url: https://sandiego.cityiq.io
websocket_url: wss://sandiego.cityiq.io/api/v2/websocket/events

# Start time for scraping and processing
start_time: 20180901T00:00:00
timezone: US/Pacific

# Caches for storing events and processed events
cache:
    token:     /tmp/cityiq/tokens
    meta:      /tmp/cityiq//meta
    objects: /tmp/cityiq/objects
    errors:    /tmp/cityiq/errors