version: '2.0'
services:
        cityiq:
            image: cityiq
            build:
                context: .
                dockerfile: Dockerfile
            environment:
                - CITYIQ_EVENTS_CACHE=/data/cache/cityiq/events
                - CITYIQ_CACHE_DIR=/data/cache/cityiq
            volumes:
                - nas1-main:/data/
volumes:
  nas1-main:
    external: true
