version: '2.0'
services:
  cityiq:
    image: cityiq
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - X_CITYIQ_EVENTS_CACHE=/data/cache/cityiq/events
        - X_CITYIQ_CACHE_DIR=/data/cache/cityiq
    volumes:
        - nas2-cache:/data/
  config:
     entrypoint: ciq_config
     command: -p
     image: cityiq
     tty: true
     volumes:
       - nas2-cache:/data/
  locations:
    command: ciq_locations
    image: cityiq
    tty: true
    volumes:
      - nas2-cache:/data/
volumes:
  nas2-cache:
    external: true
